title: "Frizk Studios Scripts Documentation"  # Your documentation title
theme: "just-the-docs"

# Optional: Configuration for Just the Docs theme
just_the_docs:
  logo: "/assets/logo.png"  # If you want to add a logo
  search_enabled: true      # Enable search functionality
  show_last_updated_time: true  # Show last updated time
  aux_links:                 # Add links to GitHub or other sites
    GitHub Repository:
      - "https://github.com/frizkstudios/fivem-scripts-docs"
