title: "Frizk Studios"  # Your documentation title
remote_theme: just-the-docs/just-the-docs

# Optional: Configuration for Just the Docs theme
just_the_docs:
  logo: "/assets/logo.png"  # If you want to add a logo
  search_enabled: true      # Enable search functionality
  show_last_updated_time: true  # Show last updated time

  color_scheme: dark

  aux_links:  # Optional links in the navigation
    "GitHub Repository":
      url: "https://github.com/frizkstudios/fivem-scripts-docs"

# Navigation structure
navigation:
  - title: "Home"
    url: "/"
  - title: "The Chop Job"
    url: "/docs/scripts/the_chop_job"
    children:
      - title: "Installation"
        url: "/docs/scripts/the_chop_job/installation"
      - title: "Usage"
        url: "/docs/scripts/the_chop_job/usage"
      - title: "Items list"
        url: "/docs/scripts/the_chop_job/item_list"
      - title: "Editable functions"
        url: "/docs/scripts/the_chop_job/editable"
      - title: "Configuration"
        url: "/docs/scripts/the_chop_job/configuration"        
  - title: "Arcade Arenas"
    url: "/docs/scripts/arcade"
    children:
      - title: "Installation"
        url: "/docs/scripts/arcade/installation"
      - title: "Usage"
        url: "/docs/scripts/arcade/usage"
      - title: "Editable functions"
        url: "/docs/scripts/arcade/editable"        
      - title: "Configuration"
        url: "/docs/scripts/arcade/configuration"