title: "Frizk Studios Scripts Documentation"  # Your documentation title
remote_theme: just-the-docs/just-the-docs

# Optional: Configuration for Just the Docs theme
just_the_docs:
  logo: "/assets/logo.png"  # If you want to add a logo
  search_enabled: true      # Enable search functionality
  show_last_updated_time: true  # Show last updated time

  aux_links:  # Optional links in the navigation
    "GitHub Repository":
      url: "https://github.com/frizkstudios/fivem-scripts-docs"

# Navigation structure
navigation:
  - title: "Home"
    url: "/"
  - title: "The Chop Job"
    url: "/docs/scripts/the_chop_job"
    children:
      - title: "Overview"
        url: "/docs/scripts/the_chop_job/overview"
      - title: "Installation"
        url: "/docs/scripts/the_chop_job/installation"
      - title: "Usage"
        url: "/docs/scripts/the_chop_job/usage"
  - title: "Advanced Server Log System"
    url: "/docs/scripts/advanced_server_log_system"
